### ISSUE TITLE
关于 | Nofated的Blog

### ISSUE THREAD

**Issue by Nofated095** [Nofated095/nofated095.github.io#1]
https://nofated095.github.io/post/about/

**Comment by KJZH001** [comment]
我这边友链加上去了= =

差点忘了这回事 = =||（大汗）

你那边什么时候看到了也加一下吧

头像：https://blog.moeworld.tech/wp-content/uploads/2019/07/KJZH001_avatar-96x96.png

站点：https://blog.moeworld.tech

描述：**探索更大的世界**
